const STORAGE_KEY = 'b612.project-checklist.v1'

const S = { done: 'done', partial: 'partial', todo: 'todo', idea: 'idea', risk: 'risk' }
function item(text, status = S.todo) { return { text, status } }

export const CHECKLIST_SECTIONS = [
  { title: '① 小屋入口 · 账号 · 安全', items: [item('b612.fyi 正式域名',S.done),item('HTTPS',S.done),item('Supabase 账号登录',S.done),item('新设备首次账号密码登录',S.done),item('本机 6 位 PIN',S.done),item('离开前台自动回锁',S.done),item('手动锁定',S.done),item('PWA 安装到手机/桌面',S.done),item('开屏动画',S.done),item('基础 health 状态检查',S.done),item('Bridge / sidecar 独立运行',S.done),item('生产 release + rollback 机制',S.done),item('Android 原生设备凭据'),item('新手机由旧设备批准'),item('单独撤销某台设备'),item('总控台 Secret Vault'),item('API Key / TTS Key 等只存服务器'),item('Capability 权限开关'),item('一键备份全部 LoveHouse 数据'),item('一键迁移/恢复'),item('Supabase 全生产 RLS 最终安全基线复核',S.risk)] },
  { title: '② 首页 · 桌面 · 外观', items: [item('首页',S.done),item('日历',S.done),item('定位',S.done),item('实时天气',S.done),item('今日卡片',S.done),item('心情入口',S.done),item('待办入口',S.done),item('每日语录',S.done),item('多套主题',S.done),item('星球玫瑰视觉',S.done),item('手机底部导航',S.done),item('桌面侧边栏',S.done),item('响应式布局',S.done),item('4×4 桌面骨架设计',S.partial),item('独立 Dock',S.partial),item('Widget 可改变尺寸/信息密度',S.partial),item('自定义桌面布局'),item('拖动 App / Widget'),item('保存自己的桌面排列'),item('统一 Accent / Theme Token'),item('旅行主题反向成为 LoveHouse 主题')] },
  { title: '③ Chat 核心骨架', items: [item('LoveHouse 自己的 Thread',S.done),item('Thread ≠ CLI/API session',S.done),item('Persona 与底层模型分离',S.done),item('Runtime Adapter',S.done),item('Codex CLI Runtime',S.done),item('Claude CLI Runtime',S.done),item('Codex 生产 E2E',S.done),item('Claude 生产 E2E',S.done),item('Claude 长期认证 token',S.done),item('Bridge 重启后 Resume',S.done),item('sidecar 重启后 Resume',S.done),item('SSE 流式回复',S.done),item('错误统一处理',S.done),item('provider session 不暴露前端',S.done),item('原生 reasoning summary 才展示',S.done),item('没有 reasoning 时显示 unavailable',S.done),item('不伪造“思考链”',S.done),item('Tool started / completed 状态',S.done),item('Usage 真实 Token',S.done),item('input token',S.done),item('cached input token',S.done),item('output token',S.done),item('reasoning/thinking token',S.done),item('quota 拿不到就 unknown',S.done),item('GPT 独立 Chat Runtime'),item('Claude API Runtime'),item('Codex/OpenAI API Runtime'),item('同一 Persona 在 CLI / API 间切换而不换 Thread')] },
  { title: '④ 自然聊天体验', items: [item('自然分段回复 v1 已完成，本地待 push/deploy',S.partial),item('生活闲聊才允许拆成多个气泡',S.done),item('工作窗口永远单气泡',S.done),item('技术解释永远单气泡',S.done),item('工单/代码/表格/教程不拆',S.done),item('最多约 5 个展示气泡',S.done),item('数据库仍保存一条完整原文',S.done),item('连续小气泡轻微发送节奏'),item('长消息折叠'),item('引用回复'),item('转发'),item('复制'),item('长按多选'),item('批量删除'),item('编辑自己的消息'),item('重新生成 AI 回复'),item('搜索聊天'),item('按日期跳转'),item('临时聊天'),item('AI 跟进问题建议',S.idea)] },
  { title: '⑤ Persona · 聊天窗口', items: [item('Codex Persona',S.done),item('Claude Persona',S.done),item('小客厅',S.done),item('G老师/GPT 独立 Runtime Persona'),item('Persona 详情页'),item('Persona 头像'),item('昵称'),item('Persona 自己的 Thread'),item('Persona 自己的 Memory Scope'),item('Persona 自己的 Archive'),item('Persona 自己的 Runtime Binding'),item('Runtime/model 切换藏在 Persona 设置内'),item('casual 生活场景'),item('work 工作场景'),item('travel 旅行场景'),item('livingroom 小客厅场景'),item('custom 自定义场景')] },
  { title: '⑥ 聊天档案 · Archive', items: [item('Raw Chat Archive 原始聊天全文'),item('一个人格一条长期 Thread'),item('聊久自动“封卷”'),item('卷册时间范围'),item('消息数量'),item('摘要'),item('标签/索引'),item('原始消息完整保留'),item('当前卷与旧卷无缝续接'),item('旧消息可以转发回当前聊天'),item('引用旧消息后回到当前 Thread'),item('Archive 搜索'),item('Archive 日期跳转'),item('Summary 只做索引、不替代原文'),item('官方 ChatGPT 聊天导入'),item('导入来源保留 platform / conversation / message ID'),item('导入内容先进入 Archive，不自动变成 Memory')] },
  { title: '⑦ Memory V2 · 长期记忆', items: [item('GPT / Claude 私有记忆隔离',S.done),item('approved Shared Memory',S.done),item('remember',S.done),item('recall',S.done),item('revise',S.done),item('open_memory',S.done),item('wake_up Starter Pack',S.done),item('revision history',S.done),item('source/provenance',S.done),item('原文需要显式展开',S.done),item('current revision',S.done),item('semantic recall',S.done),item('lexical fallback',S.done),item('中文检索',S.done),item('embedding 可重建',S.done),item('GPT / Claude actor 固定',S.done),item('Memory MCP 七工具收窄方向',S.done),item('Memory 和小客厅边界分开',S.done),item('Legacy Pending 整理工具'),item('Shared Memory 审批 UI'),item('AI 日记正式 UI'),item('短期记忆聚合页'),item('长期记忆提炼页'),item('承诺专栏'),item('偏好专栏'),item('明确要求记住的事'),item('stale：可能过时、待修订'),item('superseded 当前状态 UI'),item('自动发现“旧观点可能已经过时”')] },
  { title: '⑧ GPT / Claude 记忆档案馆', items: [item('主题档案母版',S.partial),item('变化轨迹母版',S.partial),item('原话档案'),item('时间档案'),item('万年历'),item('年 → 月 → 日进入某天记忆'),item('某天的事件/原话/变化集中查看'),item('“旧理解 → 新理解 → 修订/悬置”完整展示'),item('来源原文跳转'),item('小屋档案迁出记忆页，成为独立一级入口')] },
  { title: '⑨ WorldBook 世界书', items: ['世界书条目','完整正文','实际注入摘要','常驻触发','关键词触发','手动触发','关键词组','AND / NOT','Regex','触发概率','优先级','启用/禁用','注入位置','注入 role','扫描深度','持续轮数','递归触发（默认关闭）','WorldBook Token 预算','实际注入预览'].map(x=>item(x)) },
  { title: '⑩ Context Composer · 上下文编排器', items: ['Persona 上下文','WorldBook 上下文','Memory V2 上下文','Archive Summary','Recent Chat','时间','地点','当前现实状态','当前 scene','回复格式','Token 预算','去重','排序','裁剪','Context Preview','本轮到底注入了哪些记忆','本轮到底注入了哪些世界书','Token 来源占比','trim 信息','run id / fingerprint','Composer 挂掉时自动退回基础规则 + recent chat','防止整份 Markdown / 整段历史每轮重复灌入'].map(x=>item(x)) },
  { title: '⑪ 媒体消息基础层', items: ['MediaAsset 统一对象','图片消息','音频消息','视频消息','文件消息','位置消息','duration','width / height','thumbnail','transcript','storage reference','“发给 AI 看”与“永久保存”严格分开','显式保存到相册/图库/旅行','临时媒体自动清理'].map(x=>item(x)) },
  { title: '⑫ Voice · 语音', items: ['录音发送','STT 语音转文字','TTS 文字转语音','ElevenLabs','Persona 独立声音','用户选择输入方式','用户选择输出方式','AI 在生活聊天中自己选择文字/语音','工作窗口默认文字','手动“这段文字读给我听”','手动“把这条语音转文字”','Natural Segments 分段播放语音','播放速度/音量等基础控制'].map(x=>item(x)) },
  { title: '⑬ Realtime 实时通话', items: ['Realtime Session 独立于普通 Chat Message','实时语音通话','实时视频通话','Audio Track','Video Track','Screen Track','摄像头给 AI 看现实画面','屏幕共享','实时事件','断线恢复','通话记录/时长统计'].map(x=>item(x)) },
  { title: '⑭ 主动唤醒', items: ['主动唤醒总开关','Web 阶段默认 OFF','OFF 时绝不调用模型','Android 推送权限','推送通知','AI 醒来继续原 Persona / Thread','AI 醒来后自己决定干什么','可以找你说话','可以什么都不说','可以看记忆/整理东西','AI 自己决定下一次醒来时间','next_wake_at 持久化','wake id 防重复','认证失败不死循环','没定下次时间时服务器不擅自补','每个 Persona 可单独开关'].map(x=>item(x)) },
  { title: '⑮ 小客厅 · 社交', items: [item('三方小客厅',S.done),item('原消息时间戳',S.done),item('工单簿索引',S.done),item('Memory / LivingRoom MCP',S.done),...['更完整群聊 UI','多 AI Persona 加入','朋友圈','小圈','动态','AI 主动发朋友圈','评论/互动','消息转发到小客厅'].map(x=>item(x))] },
  { title: '⑯ 生活记录', items: [item('日记',S.done),item('语录墙',S.done),item('待办',S.done),item('心情日志',S.done),item('私密记录',S.done),item('小纸条留言板',S.done),item('全屋搜索',S.done),item('浏览记录',S.done),item('自传',S.done),...['纪念日','倒计时','小账本','收藏夹','收藏消息','收藏截图','收藏「我的思路」','标签整理'].map(x=>item(x))] },
  { title: '⑰ 音乐 · 一起听', items: ['音乐模块','网易云等音乐源 Adapter','一起听歌','当前歌曲状态','AI 知道你正在听什么','听歌过程中自然聊天','某些歌曲/歌词触发互动','听歌时长统计','音乐收藏'].map(x=>item(x)) },
  { title: '⑱ 相册 · 画廊', items: ['相册','画廊','图片收藏','截图收藏','媒体标签','日期浏览','来源关联','某张图关联到聊天/旅行/记忆','永久媒体与临时附件分开'].map(x=>item(x)) },
  { title: '⑲ 旅行手帐', items: [...['从普通聊天自然发起旅行','GPT 提议建立旅行卡','模拟旅行','现实旅行','计划行程','实际旅程','两者严格分开','手动结束旅行','预计结束时间不自动关闭','竖向长卷旅行手帐','每趟旅行独立版式','图片密集排版','地点','时间','地图','Travel Clock','Travel Calendar','中文正文','AI 英文旁白','旅行临时聊天','旅行照片显式保存','旅行颜色生成主题 Token'].map(x=>item(x)),item('手写/OCR',S.idea),item('空间回复',S.idea),item('复杂贴纸编辑器',S.idea),item('全球 GIS',S.idea)] },
  { title: '⑳ 学习 · 阅读', items: ['共读','阅读书架','共读进度','读书批注','背单词','单词本','学习统计','AI 陪读/解释'].map(x=>item(x)) },
  { title: '㉑ 健康', items: ['健康页面','心跳','睡眠','手环同步','运动数据','健康趋势','只作为生活记录，不擅自医疗诊断'].map(x=>item(x)) },
  { title: '㉒ 数据统计', items: [item('基础 Stats 页面存在',S.done),...['每日聊天条数','每周/月聊天量','Token 日历','Token 趋势','Token 热力图','Claude / Codex 分开统计','Input / cached / output / reasoning 分开','听歌时长','通话时长','主动唤醒次数','Memory 写入/修订统计'].map(x=>item(x))] },
  { title: '㉓ 游戏 · 小玩意', items: ['游戏区','收藏聊天里一起做的小游戏','BOBO','万花筒','观星室','小手机','小屋快报'].map(x=>item(x)) },
  { title: '㉔ 总控台 Control Center', items: ['独立 1×1 App 图标','House Status','AI 权限','Capability 开关','已连接服务','API 管理','Secret Vault','设备列表','新设备配对','撤销设备','Key 使用记录','维护记录','GitHub 状态','Supabase 状态','VPS 状态','Cloudflare 状态','Claude/Codex Runtime 状态','Memory 状态'].map(x=>item(x)) },
  { title: '㉕ 外部入口 · Channel Adapter', items: [item('B612 网站',S.done),...['LoveHouse Android 原生 App','Telegram','微信','其它聊天入口','所有入口共享同一个 Persona / Thread / Archive / Memory'].map(x=>item(x))] },
  { title: '㉖ Android 原生 App', items: ['Kotlin + Jetpack Compose','逐页迁移 Web 功能','稳定 /api/v1 Client API','App 不接触 service_role','App 不接触模型 Secret','App 不知道 VPS 内部端口','可替换数据库','可替换 VPS','Push Notification','主动唤醒开关','后台生成','媒体权限','麦克风','摄像头','文件','定位','系统分享入口'].map(x=>item(x)) },
  { title: '㉗ AI 工具与主动性', items: [item('Tool Event 基础协议',S.done),item('Claude/Codex Runtime 与工具显示解耦',S.done),...['LoveHouse Codex 改为主动型提示词','不再默认“没有明确命令就什么也不做”','低风险能力预授权','高风险能力单独确认','读取 Memory','搜索','读指定文件','项目状态检查','Gmail / Calendar 等已连软件入口','工具 Capability 白名单','工具调用记录'].map(x=>item(x))] },
  { title: '㉘ 工程 · 工作台', items: [item('搭建日志',S.done),item('docs/changes',S.done),item('Git 分支/commit/回滚流程',S.done),item('独立 Claude/Codex sidecar',S.done),item('精确 release 部署',S.done),...['更新记录页面','施工文件','GitHub/Cloudflare/VPS/DNS 改动自动汇总','工作台','仓库状态','部署记录','错误/health 面板','仓库收口：清旧 worktree / legacy / 重复脚本','工程资料和生活记忆严格分开'].map(x=>item(x))] },
]

export const STATUS_META={done:{label:'已完成',mark:'☑'},partial:{label:'进行中',mark:'◐'},todo:{label:'待施工',mark:'☐'},idea:{label:'灵感',mark:'◇'},risk:{label:'风险复核',mark:'!'}}
function readStore(){if(typeof window==='undefined')return{overrides:{},custom:[]};try{return JSON.parse(window.localStorage.getItem(STORAGE_KEY))||{overrides:{},custom:[]}}catch{return{overrides:{},custom:[]}}}
function writeStore(store){window.localStorage.setItem(STORAGE_KEY,JSON.stringify(store))}
export function loadProjectChecklist(){const store=readStore();return CHECKLIST_SECTIONS.map((section,sectionIndex)=>{const baseItems=section.items.map((entry,itemIndex)=>{const id=`base-${sectionIndex}-${itemIndex}`;return{id,...entry,note:'',completedAt:'',...(store.overrides?.[id]||{})}});const customItems=(store.custom||[]).filter(entry=>entry.sectionIndex===sectionIndex);return{...section,sectionIndex,items:[...baseItems,...customItems]}})}
export function saveProjectChecklistItem(entry){const store=readStore();if(entry.id.startsWith('custom-'))store.custom=(store.custom||[]).map(item=>item.id===entry.id?{...item,...entry}:item);else store.overrides={...(store.overrides||{}),[entry.id]:{status:entry.status,note:entry.note||'',completedAt:entry.completedAt||''}};writeStore(store)}
export function addProjectChecklistItem(sectionIndex,text){const store=readStore();const entry={id:`custom-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,sectionIndex,text,status:'todo',note:'',completedAt:'',custom:true};store.custom=[...(store.custom||[]),entry];writeStore(store);return entry}
export function deleteProjectChecklistItem(id){const store=readStore();if(!id.startsWith('custom-'))return;store.custom=(store.custom||[]).filter(item=>item.id!==id);writeStore(store)}
