-- MEMORY-NAMESPACE-V1
-- Adds one shared memory engine with isolated Claude, GPT, and shared spaces.
-- This migration is intentionally blocked until the P0 owner-only RLS migration
-- has replaced every public allow_all policy on the memory tables.

begin;

do $$
declare
  target_table text;
  missing_tables text[] := '{}';
  insecure_tables text[] := '{}';
  missing_owner_policies text[] := '{}';
begin
  foreach target_table in array array[
    'brain',
    'memories',
    'window_summaries',
    'memory_candidates',
    'active_threads',
    'dream_runs'
  ] loop
    if to_regclass(format('public.%I', target_table)) is null then
      missing_tables := array_append(missing_tables, target_table);
    end if;

    if exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = target_table
        and policyname = 'allow_all'
    ) then
      insecure_tables := array_append(insecure_tables, target_table);
    end if;

    if not exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = target_table
        and policyname = 'lovehouse_owner_only'
    ) then
      missing_owner_policies := array_append(missing_owner_policies, target_table);
    end if;
  end loop;

  if cardinality(missing_tables) > 0 then
    raise exception 'MEMORY-NAMESPACE-V1 blocked: missing tables: %', array_to_string(missing_tables, ', ');
  end if;

  if cardinality(insecure_tables) > 0 then
    raise exception 'MEMORY-NAMESPACE-V1 blocked: public allow_all policies remain on: %', array_to_string(insecure_tables, ', ');
  end if;

  if cardinality(missing_owner_policies) > 0 then
    raise exception 'MEMORY-NAMESPACE-V1 blocked: owner-only RLS policy missing on: %', array_to_string(missing_owner_policies, ', ');
  end if;
end
$$;

create table public.memory_spaces (
  id bigint generated by default as identity primary key,
  space_key text not null unique,
  owner_id uuid not null references auth.users(id) on delete restrict,
  display_name text not null,
  space_type text not null check (space_type in ('ai', 'shared')),
  owner_model text,
  self_description text,
  speaking_style text,
  memory_strategy text,
  profile_data jsonb not null default '{}'::jsonb
    check (jsonb_typeof(profile_data) = 'object'),
  is_active boolean not null default true,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint memory_spaces_owner_model_check check (
    (space_type = 'shared' and owner_model is null)
    or
    (space_type = 'ai' and owner_model is not null)
  )
);

comment on table public.memory_spaces is
  'LoveHouse memory namespaces and editable AI profile cards. One engine, isolated spaces.';
comment on column public.memory_spaces.profile_data is
  'Forward-compatible profile details; must remain a JSON object.';

insert into public.memory_spaces (
  space_key,
  owner_id,
  display_name,
  space_type,
  owner_model,
  memory_strategy
)
values
  (
    'claude',
    'df12b754-ea94-4289-974e-82ed506ae260'::uuid,
    'Claude / 小克',
    'ai',
    'claude',
    '只读取 Claude 专属记忆与 shared 共同记忆'
  ),
  (
    'gpt',
    'df12b754-ea94-4289-974e-82ed506ae260'::uuid,
    'GPT / G老师',
    'ai',
    'gpt',
    '只读取 GPT 专属记忆与 shared 共同记忆'
  ),
  (
    'shared',
    'df12b754-ea94-4289-974e-82ed506ae260'::uuid,
    '共同记忆',
    'shared',
    null,
    '小婷确认可由双方共同读取的内容'
  );

alter table public.memory_spaces enable row level security;

create policy memory_spaces_owner_select
  on public.memory_spaces
  for select
  to authenticated
  using ((select auth.uid()) = owner_id);

create policy memory_spaces_owner_update
  on public.memory_spaces
  for update
  to authenticated
  using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id);

revoke all privileges on table public.memory_spaces from anon, authenticated;
grant select on table public.memory_spaces to authenticated, service_role;
grant update (
  display_name,
  self_description,
  speaking_style,
  memory_strategy,
  profile_data,
  is_active,
  archived_at,
  updated_at
) on table public.memory_spaces to authenticated;
grant insert, update, delete on table public.memory_spaces to service_role;

revoke all privileges on sequence public.memory_spaces_id_seq from anon;
grant usage, select on sequence public.memory_spaces_id_seq to service_role;

do $$
declare
  target_table text;
  constraint_name text;
begin
  foreach target_table in array array[
    'brain',
    'memories',
    'window_summaries',
    'memory_candidates',
    'active_threads',
    'dream_runs'
  ] loop
    execute format(
      'alter table public.%I add column if not exists space_key text',
      target_table
    );
    execute format(
      'update public.%I set space_key = %L where space_key is null',
      target_table,
      'shared'
    );
    execute format(
      'alter table public.%I alter column space_key set default %L',
      target_table,
      'shared'
    );
    execute format(
      'alter table public.%I alter column space_key set not null',
      target_table
    );

    constraint_name := target_table || '_space_key_fkey';
    if not exists (
      select 1
      from pg_constraint
      where conrelid = format('public.%I', target_table)::regclass
        and conname = constraint_name
    ) then
      execute format(
        'alter table public.%I add constraint %I foreign key (space_key) references public.memory_spaces(space_key) on update cascade on delete restrict',
        target_table,
        constraint_name
      );
    end if;

    execute format(
      'create index if not exists %I on public.%I (space_key)',
      target_table || '_space_key_idx',
      target_table
    );
  end loop;
end
$$;

-- Self-checks. Any failure aborts and rolls back the whole migration.
do $$
declare
  target_table text;
  null_rows bigint;
begin
  if (
    select count(*)
    from public.memory_spaces
    where space_key in ('claude', 'gpt', 'shared')
  ) <> 3 then
    raise exception 'MEMORY-NAMESPACE-V1 verification failed: seed spaces are incomplete';
  end if;

  foreach target_table in array array[
    'brain',
    'memories',
    'window_summaries',
    'memory_candidates',
    'active_threads',
    'dream_runs'
  ] loop
    execute format(
      'select count(*) from public.%I where space_key is null',
      target_table
    ) into null_rows;

    if null_rows > 0 then
      raise exception 'MEMORY-NAMESPACE-V1 verification failed: %.space_key has % null rows', target_table, null_rows;
    end if;
  end loop;
end
$$;

commit;
